=== ekurz-gemini/gmp/giapi-status-service/src/main/resources/status-translator.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="TranslateStatus">
        <xs:complexType>
            <xs:choice  minOccurs="0" maxOccurs="unbounded">
                <xs:element name="Status" type="StatusType"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="dataType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="INT"/>
            <xs:enumeration value="FLOAT"/>
            <xs:enumeration value="DOUBLE"/>
            <xs:enumeration value="STRING"/>
            <xs:enumeration value="HEALTH"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="StatusType">
        <xs:sequence>
            <xs:element name="originalName" type="xs:string"/>
            <xs:element name="translatedName" type="xs:string"/>
            <xs:element name="originalType" type="dataType"/>
            <xs:element name="translatedType" type="dataType"/>
            <xs:element name="Maps" type="MapList"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="MapList">
        <xs:choice  minOccurs="1" maxOccurs="unbounded">
            <xs:element name="Map" type="MapType"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="MapType">
        <xs:sequence>
            <xs:element name="from" type="xs:string"/>
            <xs:element name="to" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ekurz-gemini/gmp/instances/gpi/src/main/config/status-translator.xml
<?xml version="1.0"?>
<TranslateStatus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="status-translator.xsd">
    <Status>
        <originalName>ifsFilter</originalName>
        <translatedName>ifsFilter.gemini</translatedName>
        <originalType>STRING</originalType>
        <translatedType>STRING</translatedType>
        <Maps>
            <Map>
                <from>Y</from>
                <to>IFSFILT_Y_G1211</to>
            </Map>
            <Map>
                <from>J</from>
                <to>IFSFILT_J_G1212</to>
            </Map>
            <Map>
                <from>H</from>
                <to>IFSFILT_H_G1213</to>
            </Map>
            <Map>
                <from>K1</from>
                <to>IFSFILT_K1_G1214</to>
            </Map>
            <Map>
                <from>K2</from>
                <to>IFSFILT_K2_G1215</to>
            </Map>
            <Map>
                <from>UNKNOWN</from>
                <to>UNKNOWN</to>
            </Map>
        </Maps>
    </Status>
    <Status>
        <originalName>aoWfsFilter</originalName>
        <translatedName>aoWfsFilter.gemini</translatedName>
        <originalType>STRING</originalType>
        <translatedType>STRING</translatedType>
        <Maps>
            <Map>
                <from>600NM_LOW_CUTOFF</from>
                <to>AOFILT_600NM_G1221</to>
            </Map>
            <Map>
                <from>700NM_LOW_CUTOFF</from>
                <to>AOFILT_700NM_G1222</to>
            </Map>
            <Map>
                <from>800NM_LOW_CUTOFF</from>
                <to>AOFILT_800NM_G1223</to>
            </Map>
            <Map>
                <from>900NM_LOW_CUTOFF</from>
                <to>AOFILT_900NM_G1224</to>
            </Map>
            <Map>
                <from>910_900NM_BAND_PASS</from>
                <to>AOFILT_910_900NM_BAND_PASS_G1225</to>
            </Map>
            <Map>
                <from>OPEN</from>
                <to>AOFILT_OPEN_G1226</to>
            </Map>
            <Map>
                <from>UNKNOWN</from>
                <to>UNKNOWN</to>
            </Map>
        </Maps>
    </Status>
</TranslateStatus>

=== ekurz-gemini/gmp/integration-tests/src/test/resources/conf/status-translator.xml
<?xml version="1.0"?>
<TranslateStatus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="status-translator.xsd">
    <Status>
        <originalName>old</originalName>
        <translatedName>new</translatedName>
        <originalType>INT</originalType>
        <translatedType>HEALTH</translatedType>
        <default>BAD</default>
        <Maps>
            <Map>
                <from>0</from>
                <to>GOOD</to>
            </Map>
            <Map>
                <from>1</from>
                <to>WARNING</to>
            </Map>
            <Map>
                <from>2</from>
                <to>BAD</to>
            </Map>
        </Maps>
    </Status>
</TranslateStatus>
