=== ekurz-gemini/gmp/gmp-epics-to-status/src/main/resources/gmp-epics-to-status-mapping.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation>
            Schema file defining the structure of the configuration file used by the gmp-epics-to-status module
            to map EPICS channels to GIAPI status items.
        </xs:documentation>
    </xs:annotation>
    <xs:element name="Channels">
        <xs:annotation>
            <xs:documentation>
                The 'Channels' root element, can have any number of 'SimpleChannel', 'AlarmChannel' and
                'HealthChannel' child elements, in any order.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice  minOccurs="0" maxOccurs="unbounded">
                <xs:element name="SimpleChannel" type="SimpleChannelType"/>
                <xs:element name="AlarmChannel" type="AlarmChannelType"/>
                <xs:element name="HealthChannel" type="HealthChannelType"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="dataType">
        <xs:annotation>
            <xs:documentation>
                These are the 4 supported data types. The mapping is as follows:
                Type      Java         Epics
                INT       Integer      DBR_Int
                FLOAT     Float        DBR_Float
                DOUBLE    Double       DBR_Double
                STRING    String       DBR_String
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="INT"/>
            <xs:enumeration value="FLOAT"/>
            <xs:enumeration value="DOUBLE"/>
            <xs:enumeration value="STRING"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="BaseChannelType">
        <xs:sequence>
            <xs:element name="statusitem" type="xs:string"/>
            <xs:element name="epicschannel" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="HealthChannelType">
        <xs:annotation>
            <xs:documentation>
                Type for health channels. The EPICS channel needs to be a DBR_String, and it will be published as
                a HealthStatusItem.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BaseChannelType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="SimpleChannelType">
        <xs:annotation>
            <xs:documentation>
                Type for 'normal' channels.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BaseChannelType">
                <xs:sequence>
                    <xs:element name="type" type="dataType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="AlarmChannelType">
        <xs:annotation>
            <xs:documentation>
                Type for alarm channels. The configuration is the same as 'normal' channels.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="SimpleChannelType"/>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== ekurz-gemini/gmp/gmp-epics-to-status/src/main/resources/gmp-epics-to-status-mapping.xml
<?xml version="1.0"?>
<Channels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="gmp-epics-to-status-mapping.xsd">
	<SimpleChannel>
		<statusitem>statusitemint</statusitem>
		<epicschannel>epicschannelint</epicschannel>
		<type>INT</type>
	</SimpleChannel>
	<SimpleChannel>
		<statusitem>statusitemfloat</statusitem>
		<epicschannel>epicschannelfloat</epicschannel>
		<type>FLOAT</type>
	</SimpleChannel>
    <SimpleChannel>
		<statusitem>statusitemdouble</statusitem>
		<epicschannel>epicschanneldouble</epicschannel>
		<type>DOUBLE</type>
	</SimpleChannel>
	<SimpleChannel>
		<statusitem>statusitemstring</statusitem>
		<epicschannel>epicschannelstring</epicschannel>
		<type>STRING</type>
	</SimpleChannel>
	<AlarmChannel>
		<statusitem>giapialarmint</statusitem>
		<epicschannel>epicsalarmint</epicschannel>
		<type>INT</type>
	</AlarmChannel>
	<AlarmChannel>
		<statusitem>giapialarmfloat</statusitem>
		<epicschannel>epicsalarmfloat</epicschannel>
		<type>FLOAT</type>
	</AlarmChannel>
    <AlarmChannel>
		<statusitem>giapialarmdouble</statusitem>
		<epicschannel>epicsalarmdouble</epicschannel>
		<type>DOUBLE</type>
	</AlarmChannel>
	<AlarmChannel>
		<statusitem>giapialarmstring</statusitem>
		<epicschannel>epicsalarmstring</epicschannel>
		<type>STRING</type>
	</AlarmChannel>
    <HealthChannel>
        <statusitem>giapihealth1</statusitem>
        <epicschannel>epicshealth1</epicschannel>
    </HealthChannel>
    <HealthChannel>
        <statusitem>giapihealth2</statusitem>
        <epicschannel>epicshealth2</epicschannel>
    </HealthChannel>
    <HealthChannel>
        <statusitem>giapihealth3</statusitem>
        <epicschannel>epicshealth3</epicschannel>
    </HealthChannel>
</Channels>
