=== ekurz-gemini/gmp/app/gmp-server/giapi-epics-status-mapping.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="channels">
	<xs:complexType>
	<xs:sequence>
		<xs:element name="channel" maxOccurs="unbounded">
			<xs:complexType>
			<xs:sequence>
				<xs:element name="giapiname" type="xs:string"/>
				<xs:element name="epicsname" type="xs:string"/>
				<xs:element name="type" type="xs:string"/>
				<xs:element name="initial" type="xs:anyType"/>
			</xs:sequence>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== ekurz-gemini/gmp/app/gmp-server/giapi-epics-status-mapping.xml
<?xml version="1.0"?>
<channels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="giapi-epics-status-mapping.xsd">
	<channel>
		<giapiname>giapiname</giapiname>
		<epicsname>epicsname</epicsname>
		<type>INT</type>
		<initial>2</initial>
	</channel>
	<channel>
		<giapiname>giapiname2</giapiname>
		<epicsname>epicsname2</epicsname>
		<type>INT</type>
		<initial>3</initial>
	</channel>
</channels>
