=== ekurz-gemini/gmp/gmp-epics-status-service/src/main/resources/giapi-epics-status-mapping.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Channels">
        <xs:complexType>
            <xs:choice  minOccurs="0" maxOccurs="unbounded">
                <xs:element name="SimpleChannel" type="SimpleChannelType"/>
                <xs:element name="AlarmChannel" type="AlarmChannelType"/>
                <xs:element name="HealthChannel" type="HealthChannelType"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="dataType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="INT"/>
            <xs:enumeration value="FLOAT"/>
            <xs:enumeration value="DOUBLE"/>
            <xs:enumeration value="STRING"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="BaseChannelType">
        <xs:sequence>
            <xs:element name="giapiname" type="xs:string"/>
            <xs:element name="epicsname" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="HealthChannelType">
        <xs:complexContent>
            <xs:extension base="BaseChannelType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="SimpleChannelType">
        <xs:complexContent>
            <xs:extension base="BaseChannelType">
                <xs:sequence>
                    <xs:element name="type" type="dataType"/>
                    <xs:element name="initial" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="AlarmChannelType">
        <xs:complexContent>
            <xs:extension base="SimpleChannelType"/>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== ekurz-gemini/gmp/dist/gmp-server/src/main/etc/conf/giapi-epics-status-mapping.xml
<?xml version="1.0"?>
<Channels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="giapi-epics-status-mapping.xsd">
	<ChannelConfig>
		<giapiname>giapiname</giapiname>
		<epicsname>epicsname</epicsname>
		<type>INT</type>
		<initial>2</initial>
	</ChannelConfig>
	<ChannelConfig>
		<giapiname>giapiname2</giapiname>
		<epicsname>epicsname2</epicsname>
		<type>FLOAT</type>
		<initial>3</initial>
	</ChannelConfig>
	<ChannelConfig>
		<giapiname>giapiname3</giapiname>
		<epicsname>epicsname3</epicsname>
		<type>DOUBLE</type>
		<initial>3</initial>
	</ChannelConfig>
	<ChannelConfig>
		<giapiname>giapiname4</giapiname>
		<epicsname>epicsname4</epicsname>
		<type>STRING</type>
		<initial>hola</initial>
	</ChannelConfig>
</Channels>

=== ekurz-gemini/gmp/instances/igrins2/src/main/config/giapi-epics-status-mapping.xml
<?xml version="1.0"?>
    
<!--
Copyright RSAA, The Korean Astronomy and Space Sciend Institue

The Igrins2 instrument. 
 Project partners:
    The Gemini Observatory (Gemini, AURA)
-->

<Channels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="giapi-epics-status-mapping.xsd">

  <HealthChannel>
    <giapiname>sad.health</giapiname>
    <epicsname>sad.health</epicsname>
  </HealthChannel>
  <SimpleChannel>
    <giapiname>sad.health_msg</giapiname>
    <epicsname>sad.health_msg</epicsname>
    <type>STRING</type>
    <initial></initial>
  </SimpleChannel>
  <SimpleChannel>
    <giapiname>sad:detk:temp</giapiname>
    <epicsname>sad:detk:temp</epicsname>
    <type>FLOAT</type>
    <initial>0</initial>
  </SimpleChannel>
  <SimpleChannel>
    <giapiname>sad:deth:temp</giapiname>
    <epicsname>sad:deth:temp</epicsname>
    <type>FLOAT</type>
    <initial>0</initial>
  </SimpleChannel>

  <SimpleChannel>
    <giapiname>sad:heartbeat</giapiname>
    <epicsname>sad:heartbeat</epicsname>
    <type>INT</type>
    <initial>0</initial>
  </SimpleChannel>
   <SimpleChannel>
      <giapiname>sad:bench:temp</giapiname>
      <epicsname>sad:bench:temp</epicsname>
      <type>FLOAT</type>
      <initial>0.0</initial>
   </SimpleChannel>
   <SimpleChannel>
      <giapiname>sad:bench:heater</giapiname>
      <epicsname>sad:bench:heater</epicsname>
      <type>FLOAT</type>
      <initial>0.0</initial>
   </SimpleChannel>
   <SimpleChannel>
      <giapiname>sad:bench:radShield</giapiname>
      <epicsname>sad:bench:radShield</epicsname>
      <type>FLOAT</type>
      <initial>0.0</initial>
   </SimpleChannel>
   <SimpleChannel>
      <giapiname>sad:bench:coldStop</giapiname>
      <epicsname>sad:bench:coldStop</epicsname>
      <type>FLOAT</type>
      <initial>0.0</initial>
   </SimpleChannel>
   <SimpleChannel>
      <giapiname>sad:bench:iobarrel</giapiname>
      <epicsname>sad:bench:iobarrel</epicsname>
      <type>FLOAT</type>
      <initial>0.0</initial>
   </SimpleChannel>
   <SimpleChannel>
      <giapiname>sad:bench:charcoalBox</giapiname>
      <epicsname>sad:bench:charcoalBox</epicsname>
      <type>FLOAT</type>
      <initial>0.0</initial>
   </SimpleChannel>
   <SimpleChannel>
      <giapiname>sad:bench:imGrating</giapiname>
      <epicsname>sad:bench:imGrating</epicsname>
      <type>FLOAT</type>
      <initial>0.0</initial>
   </SimpleChannel>
   <SimpleChannel>
      <giapiname>sad:bench:coldHeadFirst</giapiname>
      <epicsname>sad:bench:coldHeadFirst</epicsname>
      <type>FLOAT</type>
      <initial>0.0</initial>
   </SimpleChannel>
   <SimpleChannel>
      <giapiname>sad:bench:coldHeadSecond</giapiname>
      <epicsname>sad:bench:coldHeadSecond</epicsname>
      <type>FLOAT</type>
      <initial>0.0</initial>
   </SimpleChannel>
   <SimpleChannel>
      <giapiname>sad:dch:temp</giapiname>
      <epicsname>sad:dch:temp</epicsname>
      <type>FLOAT</type>
      <initial>0.0</initial>
   </SimpleChannel>
   <SimpleChannel>
      <giapiname>sad:dch:tempHeater</giapiname>
      <epicsname>sad:dch:tempHeater</epicsname>
      <type>FLOAT</type>
      <initial>0.0</initial>
   </SimpleChannel>
   <SimpleChannel>
      <giapiname>sad:dck:temp</giapiname>
      <epicsname>sad:dck:temp</epicsname>
      <type>FLOAT</type>
      <initial>0.0</initial>
   </SimpleChannel>
   <SimpleChannel>
      <giapiname>sad:dck:tempHeater</giapiname>
      <epicsname>sad:dck:tempHeater</epicsname>
      <type>FLOAT</type>
      <initial>0.0</initial>
   </SimpleChannel>
   <SimpleChannel>
      <giapiname>sad:dcs:temp</giapiname>
      <epicsname>sad:dcs:temp</epicsname>
      <type>FLOAT</type>
      <initial>0.0</initial>
   </SimpleChannel>
   <SimpleChannel>
      <giapiname>sad:dcs:tempHeater</giapiname>
      <epicsname>sad:dcs:tempHeater</epicsname>
      <type>FLOAT</type>
      <initial>0.0</initial>
   </SimpleChannel>
</Channels>

=== ekurz-gemini/gmp/src/main/config/giapi-epics-status-mapping.xml
<?xml version="1.0"?>
<Channels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="giapi-epics-status-mapping.xsd">

    <!-- Channels for integration tests -->
    <SimpleChannel>
        <giapiname>gpi:status1</giapiname>
        <epicsname>status1</epicsname>
        <type>INT</type>
        <initial>2</initial>
    </SimpleChannel>
    <SimpleChannel>
        <giapiname>gpi:status2</giapiname>
        <epicsname>status2</epicsname>
        <type>INT</type>
        <initial>2</initial>
    </SimpleChannel>
    <AlarmChannel>
        <giapiname>gpi:alarm1</giapiname>
        <epicsname>alarm1</epicsname>
        <type>INT</type>
        <initial>2</initial>
    </AlarmChannel>
    <HealthChannel>
        <giapiname>gpi:health1</giapiname>
        <epicsname>health1</epicsname>
    </HealthChannel>

    <HealthChannel>
        <giapiname>gpi:gds:health</giapiname>
        <epicsname>gds:health</epicsname>
    </HealthChannel>
</Channels>
